# Generated by Django 4.1.5 on 2023-05-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_alter_userdetails_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='department',
        ),
    ]
