# Generated by Django 4.1.5 on 2023-05-07 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_remove_userdetails_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='materials',
        ),
    ]
